sudo: required
services:
  - docker
language: python
python:
  - 3.5
install:
  - pip install -r backend/requirements/dev.txt

  - nvm install 7.9.0
  - npm install -g @angular/cli
  - cd frontend && npm install && cd -
script:
  - cd backend
  - pycodestyle --exclude='apps/volontulo/migrations/*,node_modules,.ropeproject' .
  - pylint apps
  - export VOLONTULO_SECRET_KEY="a63eb5ef-3b25-4595-846a-5d97d99486f0"
  - coverage run --source='./apps' manage.py test --settings=volontulo_org.settings.dev_local -v 3
  - coverage xml
  - cd apps/volontulo && npm install && npm build && cd -
  - cd ..

  - cd frontend
  - ng lint
  - ng test --single-run --code-coverage --browsers HeadlessChrome
  - cd ..
after_success:
  - codecov --file backend/coverage.xml
  - codecov --file frontend/coverage/lcov.info

  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then
      export REPO=codeforpoznan/volontulo;
      export TAG=latest;
      docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker build -f Dockerfile -t $REPO:$TAG .;
      docker push $REPO;

      source ~/virtualenv/python2.7/bin/activate;
      pip install fabric;
      fab -p $SSH_PASSWORD update;
    fi
