frontend:
  image: codeforpoznan/volontulo-frontend
  # build: frontend
  command: bash docker-entrypoint.sh
  # command: tail -f /dev/null
  # command: npm run ssr
  ports:
    - 4200:4200
  links:
    - backend:backend
  volumes:
    - ./frontend:/volontulo/frontend

backend:
  image: codeforpoznan/volontulo-backend
  # build: backend
  command: bash docker-entrypoint.sh
  # command: tail -f /dev/null
  environment:
    DJANGO_SETTINGS_MODULE: volontulo_org.settings.dev
    VOLONTULO_SECRET_KEY: a63eb5ef-3b25-4595-846a-5d97d99486f0
    VOLONTULO_DB_HOST: db
    VOLONTULO_DB_PASS: volontulo
  ports:
    - 8000:8000
  links:
    - db:db
  volumes:
    - ./backend:/volontulo/backend
    - /volontulo/backend/apps/volontulo/node_modules

db:
  image: postgres
  # ports:
  #   - 5432:5432
  environment:
    POSTGRES_DB: volontulo
    POSTGRES_USER: volontulo
    POSTGRES_PASSWORD: volontulo
