# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volontulo', '0008_remove_offerimage_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationgallery',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationgallery',
            name='published_by',
        ),
        migrations.DeleteModel(
            name='OrganizationGallery',
        ),
    ]
