# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volontulo', '0010_auto_20171115_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
