# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-03 20:19
from __future__ import unicode_literals

import apps.volontulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontulo', '0012_auto_20180228_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerimage',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.volontulo.models.upload_to_offers),
        ),
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
