# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volontulo', '0015_remove_offer_action_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status_old',
        ),
    ]
